FROM node:18-alpine AS builder
RUN apk add g++ make py3-pip

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

ARG ADMIN_URL_PROD
ENV ADMIN_URL_PROD=${ADMIN_URL_PROD}

RUN npm run build

FROM nginx:alpine
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
